spring:
  application:
    name: FastFoodApp
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/fast_food
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
server:
  port: 8082